# Generated by Django 4.2.23 on 2026-02-28 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Donor/')),
                ('bloodgroup', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('bloodgroup_verified', models.BooleanField(default=False, help_text='Blood group verified by lab technician on first donation')),
                ('bloodgroup_verified_at', models.DateTimeField(blank=True, null=True)),
                ('county', models.CharField(blank=True, choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ('Murang’a', 'Murang’a'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita-Taveta', 'Taita-Taveta'), ('Tana River', 'Tana River'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=50, null=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.PositiveIntegerField(default=0, help_text='Points earned by donor for successful donations')),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloodgroup_verified_by', models.ForeignKey(blank=True, help_text='lab tech who verified the blood group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donor_bloodgroups', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='DonorEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('good_health', models.BooleanField(default=True)),
                ('travel_history', models.BooleanField(default=False)),
                ('pregnant', models.BooleanField(default=False)),
                ('medical_conditions', models.TextField(blank=True, default='')),
                ('approved', models.BooleanField(default=False)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
            options={
                'verbose_name': 'Donor Eligibility',
                'verbose_name_plural': 'Donor Eligibilities',
            },
        ),
        migrations.CreateModel(
            name='BloodDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('unit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_seen', models.BooleanField(default=False)),
                ('approved_at_phlebotomist', models.DateTimeField(blank=True, null=True)),
                ('completed_at_phlebotomist', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, choices=[('phlebotomist', 'Phlebotomist'), ('admin', 'Admin')], max_length=15, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('phlebotomist', 'Phlebotomist'), ('donor', 'Donor'), ('admin', 'Admin')], max_length=15, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('stock_added_by_phlebotomist', models.BooleanField(default=False)),
                ('approved_by_phlebotomist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phlebotomist_approved_donations', to=settings.AUTH_USER_MODEL)),
                ('completed_by_phlebotomist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phlebotomist_completed_donations', to=settings.AUTH_USER_MODEL)),
                ('donation_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.donationcenter')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
            options={
                'verbose_name': 'Blood Donation',
                'verbose_name_plural': 'Blood Donations',
                'ordering': ['-date'],
            },
        ),
    ]
