# Generated by Django 4.2.23 on 2026-02-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0001_initial'),
        ('phlebotomist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='phlebotomist',
            field=models.ForeignKey(blank=True, help_text='Phlebotomist responsible for this donation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='phlebotomist.phlebotomist'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['bloodgroup'], name='donor_donor_bloodgr_7e32a9_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['county'], name='donor_donor_county_2f63c8_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['last_donation_date'], name='donor_donor_last_do_fa4fc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_donor_user'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.UniqueConstraint(fields=('mobile',), name='unique_donor_mobile'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id__isnull', False)), fields=('national_id',), name='unique_donor_national_id'),
        ),
    ]
