# Generated by Django 4.2.23 on 2025-08-09 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurse', '0001_initial'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nurse.nurse'),
        ),
    ]
