# Generated by Django 4.2.23 on 2026-03-01 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='unit',
            field=models.PositiveIntegerField(blank=True, default=450, null=True),
        ),
    ]
