# Generated by Django 4.2.23 on 2026-02-27 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['bloodgroup'], name='donor_donor_bloodgr_7e32a9_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['county'], name='donor_donor_county_2f63c8_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['last_donation_date'], name='donor_donor_last_do_fa4fc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_donor_user'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.UniqueConstraint(fields=('mobile',), name='unique_donor_mobile'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id__isnull', False)), fields=('national_id',), name='unique_donor_national_id'),
        ),
    ]
