# Generated by Django 4.2.23 on 2025-08-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='willing_to_donate',
        ),
    ]
