# Generated by Django 4.2.23 on 2025-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_donor_willing_to_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='stock_added_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='stock_added_by_nurse',
            field=models.BooleanField(default=False),
        ),
    ]
