# Generated by Django 4.2.23 on 2026-03-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_blooddonate_date_alter_blooddonate_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='adverse_event',
            field=models.CharField(choices=[('none', 'None'), ('hematoma', 'Hematoma'), ('fainting', 'Fainting/Syncope'), ('nausea', 'Nausea/Vomiting'), ('pain', 'Excessive Pain'), ('other', 'Other')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='adverse_event_details',
            field=models.TextField(blank=True, help_text='Description of adverse event if occurred'),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='arm_used',
            field=models.CharField(blank=True, choices=[('left', 'Left Arm'), ('right', 'Right Arm')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='attempts_count',
            field=models.IntegerField(default=1, help_text='Number of venipuncture attempts'),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='bleed_completion',
            field=models.CharField(choices=[('complete', 'Complete - Full Unit'), ('partial', 'Partial - Underweight'), ('incomplete', 'Incomplete - Stopped Early')], default='complete', max_length=20),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='bleed_time_end',
            field=models.TimeField(blank=True, help_text='Time when blood collection completed', null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='bleed_time_start',
            field=models.TimeField(blank=True, help_text='Time when blood collection started', null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic blood pressure (bottom number)', null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic blood pressure (top number)', null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='collection_notes',
            field=models.TextField(blank=True, help_text='General notes about the collection process'),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='donation_type',
            field=models.CharField(choices=[('whole_blood', 'Whole Blood'), ('double_red', 'Double Red Cells'), ('platelets', 'Platelets'), ('plasma', 'Plasma'), ('pediatric', 'Pediatric')], default='whole_blood', max_length=20),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='haemoglobin',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Haemoglobin level in g/dL', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='phlebotomist_notes',
            field=models.TextField(blank=True, help_text="Phlebotomist's observations during collection"),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='pulse',
            field=models.IntegerField(blank=True, help_text='Heart rate in beats per minute', null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='vein_quality',
            field=models.CharField(blank=True, choices=[('good', 'Good - Easy access'), ('fair', 'Fair - Acceptable'), ('poor', 'Poor - Difficult')], max_length=20, null=True),
        ),
    ]
