# Generated by Django 4.2.23 on 2026-03-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_blooddonate_adverse_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
