# Generated by Django 4.2.23 on 2025-08-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_blooddonate_stock_added_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
