# Generated by Django 4.2.23 on 2025-08-14 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0005_alter_blooddonate_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonate',
            old_name='approved_at',
            new_name='approved_at_admin',
        ),
        migrations.RemoveField(
            model_name='blooddonate',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='approved_at_nurse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='approved_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='approved_by_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_approved_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('nurse', 'Nurse'), ('donor', 'Donor')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='completed_at_admin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='completed_at_nurse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='completed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_completed_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='completed_by_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_completed_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='rejected_by',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('nurse', 'Nurse')], max_length=10, null=True),
        ),
    ]
