# Generated by Django 4.2.23 on 2025-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_alter_donor_bloodgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='dob',
        ),
        migrations.AddField(
            model_name='donor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
