# Generated by Django 4.2.23 on 2025-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_remove_blooddonate_dob_donor_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='unit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
