# Generated by Django 4.2.23 on 2025-08-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_alter_blooddonate_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='blooddonate',
            name='notes',
        ),
    ]
