# Generated by Django 4.2.23 on 2025-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_remove_blooddonate_disease_remove_blooddonate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
