# Generated by Django 4.2.23 on 2025-09-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0015_remove_appointment_approved_at_admin_and_more'),
        ('donor', '0012_donor_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='approved_at_admin',
        ),
        migrations.RemoveField(
            model_name='blooddonate',
            name='approved_by_admin',
        ),
        migrations.RemoveField(
            model_name='blooddonate',
            name='completed_at_admin',
        ),
        migrations.RemoveField(
            model_name='blooddonate',
            name='completed_by_admin',
        ),
        migrations.RemoveField(
            model_name='blooddonate',
            name='stock_added_by_admin',
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse'), ('donor', 'Donor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='nurse',
            field=models.ForeignKey(blank=True, help_text='Nurse responsible for this donation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nurse.nurse'),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='rejected_by',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse')], max_length=10, null=True),
        ),
    ]
