# Generated by Django 4.2.23 on 2025-10-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0017_remove_appointment_notes'),
        ('blood', '0016_remove_donorbloodrequest_approved_by_nurse_and_more'),
        ('donor', '0014_alter_donor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorBloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.PositiveIntegerField()),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('unit', models.PositiveIntegerField(default=450, help_text='Requested amount in ml')),
                ('urgency_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=20)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_seen', models.BooleanField(default=False)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at_nurse', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=20, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=20, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('completed_at_nurse', models.DateTimeField(blank=True, null=True)),
                ('approved_by_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_donor_patient_requests_nurse', to='nurse.nurse')),
                ('completed_by_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_donor_patient_requests_nurse', to='nurse.nurse')),
                ('donation_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.donationcenter')),
                ('request_by_donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_patient_requests', to='donor.donor')),
            ],
        ),
    ]
