# Generated by Django 4.2.23 on 2025-10-11 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0015_donorbloodrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='approved_at_nurse',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='approved_by_nurse',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='completed_at_nurse',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='completed_by_nurse',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='patient_dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='patient_first_name',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='patient_last_name',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
    ]
