# Generated by Django 4.2.23 on 2025-10-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0016_remove_donorbloodrequest_approved_at_nurse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='reason',
        ),
    ]
