# Generated by Django 4.2.23 on 2025-10-23 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0017_remove_donorbloodrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='bloodgroup_verified',
            field=models.BooleanField(default=False, help_text='Blood group verified by nurse on first donation'),
        ),
        migrations.AddField(
            model_name='donor',
            name='bloodgroup_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='bloodgroup_verified_by',
            field=models.ForeignKey(blank=True, help_text='Nurse who verified the blood group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donor_bloodgroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
