# Generated by Django 4.2.23 on 2025-11-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0019_remove_donor_address_donor_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='urgency_level',
        ),
    ]
