# Generated by Django 4.2.23 on 2026-02-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_technician', '0003_remove_blooddispatch_inventory_item_and_more'),
        ('blood', '0026_alter_stockunit_barcode_bloodbagbarcode_and_more'),
        ('donor', '0020_remove_donorbloodrequest_urgency_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donorbloodrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donor Blood Request', 'verbose_name_plural': 'Donor Blood Requests'},
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='stock_deducted',
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_donor_requests', to='blood_bank_technician.bloodbanktechprofile'),
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_donor_requests', to='blood_bank_technician.bloodbanktechprofile'),
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_donor_requests', to='blood_bank_technician.bloodbanktechprofile'),
        ),
        migrations.AlterField(
            model_name='donorbloodrequest',
            name='contact_number',
            field=models.CharField(default='0700000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donorbloodrequest',
            name='donation_center',
            field=models.ForeignKey(default=2, help_text='Blood bank center to fulfill this request', on_delete=django.db.models.deletion.CASCADE, to='blood.donationcenter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donorbloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Ready for Pickup'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
