# Generated by Django 4.2.23 on 2026-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankTechProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('collected_by_name', models.CharField(max_length=200)),
                ('collected_by_id', models.CharField(max_length=50)),
                ('collection_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blood Dispatch',
                'verbose_name_plural': 'Blood Dispatches',
                'ordering': ['-dispatch_date'],
            },
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('storage_location', models.CharField(blank=True, help_text="e.g., 'Rack A, Shelf 2'", max_length=50)),
                ('date_stored', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('dispatched', 'Dispatched'), ('expired', 'Expired'), ('discarded', 'Discarded')], default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Blood Inventory',
                'verbose_name_plural': 'Blood Inventory',
                'ordering': ['expiry_date', 'date_stored'],
            },
        ),
    ]
