# Generated by Django 4.2.23 on 2026-02-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankTechProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='bloodbank_profiles/')),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blood Bank Technician Profile',
                'verbose_name_plural': 'Blood Bank Technician Profiles',
            },
        ),
        migrations.CreateModel(
            name='BloodDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('collected_by_name', models.CharField(help_text='Name of hospital staff who collected', max_length=200)),
                ('collected_by_id', models.CharField(help_text='ID number of hospital staff', max_length=50)),
                ('collected_by_phone', models.CharField(blank=True, help_text='Contact phone of hospital staff', max_length=15)),
                ('collection_time', models.DateTimeField(help_text='When the blood was picked up')),
                ('hospital_authorization', models.CharField(blank=True, help_text='Authorization number/reference from hospital', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Pickup'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered to Hospital'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_to', models.CharField(blank=True, max_length=200)),
                ('delivery_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blood Dispatch',
                'verbose_name_plural': 'Blood Dispatches',
                'ordering': ['-dispatch_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('expiring', 'Expiring Soon'), ('out_of_stock', 'Out of Stock')], max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='blood.donationcenter')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='blood_bank_technician.bloodbanktechprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_type', models.CharField(choices=[('request_received', 'Request Received'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('ready_for_pickup', 'Ready for Pickup'), ('dispatched', 'Dispatched'), ('follow_up', 'Follow Up'), ('general', 'General')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('blood_bank_tech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_communications', to='blood_bank_technician.bloodbanktechprofile')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
