# Generated by Django 4.2.23 on 2026-02-24 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_technologist', '0001_initial'),
        ('patient', '0010_remove_bloodrequest_urgency_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0024_alter_dailyfactchallenge_options_and_more'),
        ('blood_bank_technician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodinventory',
            name='blood_test',
            field=models.OneToOneField(limit_choices_to={'result': 'safe'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='lab_technologist.bloodtest'),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='reserved_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_units', to='patient.bloodrequest'),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='stock_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='blood.stockunit'),
        ),
        migrations.AddField(
            model_name='blooddispatch',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='patient.bloodrequest'),
        ),
        migrations.AddField(
            model_name='blooddispatch',
            name='dispatched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_made', to='blood_bank_technician.bloodbanktechprofile'),
        ),
        migrations.AddField(
            model_name='blooddispatch',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='blood_bank_technician.bloodinventory'),
        ),
        migrations.AddField(
            model_name='bloodbanktechprofile',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_bank_technicians', to='blood.donationcenter'),
        ),
        migrations.AddField(
            model_name='bloodbanktechprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_bank_tech_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
