# Generated by Django 4.2.23 on 2026-02-28 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_bank_technician', '0001_initial'),
        ('hospital', '0001_initial'),
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalcommunication',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='hospitalcommunication',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='hospital.hospitalbloodrequest'),
        ),
        migrations.AddField(
            model_name='blooddispatch',
            name='dispatched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_made', to='blood_bank_technician.bloodbanktechprofile'),
        ),
        migrations.AddField(
            model_name='blooddispatch',
            name='hospital',
            field=models.ForeignKey(help_text='Hospital receiving the blood', on_delete=django.db.models.deletion.CASCADE, related_name='received_dispatches', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='blooddispatch',
            name='hospital_request',
            field=models.ForeignKey(help_text='Hospital blood request this dispatch fulfills', on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='hospital.hospitalbloodrequest'),
        ),
        migrations.AddField(
            model_name='blooddispatch',
            name='stock_unit',
            field=models.ForeignKey(help_text='Stock unit that was dispatched', on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='blood.stockunit'),
        ),
        migrations.AddField(
            model_name='bloodbanktechprofile',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_bank_technicians', to='blood.donationcenter'),
        ),
        migrations.AddField(
            model_name='bloodbanktechprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_bank_tech_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='bloodbanktechprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_bloodbank_tech_user'),
        ),
    ]
