# Generated by Django 4.2.23 on 2026-02-25 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0026_alter_stockunit_barcode_bloodbagbarcode_and_more'),
        ('blood_bank_technician', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddispatch',
            name='inventory_item',
        ),
        migrations.AddField(
            model_name='blooddispatch',
            name='stock_unit',
            field=models.ForeignKey(default=1, help_text='Stock unit that was dispatched', on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='blood.stockunit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BloodInventory',
        ),
    ]
