# Generated by Django 4.2.23 on 2026-03-05 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_bank_technician', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbanktechprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin approved this technician', null=True),
        ),
        migrations.AddField(
            model_name='bloodbanktechprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this technician', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_blood_bank_techs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodbanktechprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether admin has approved this technician'),
        ),
    ]
