# Generated by Django 4.2.23 on 2026-02-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_technician', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodbanktechprofile',
            options={'verbose_name': 'Blood Bank Technician Profile', 'verbose_name_plural': 'Blood Bank Technician Profiles'},
        ),
        migrations.AddConstraint(
            model_name='bloodbanktechprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_bloodbank_tech_user'),
        ),
    ]
