# Generated by Django 4.2.23 on 2026-02-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0021_alter_donorbloodrequest_options_and_more'),
        ('patient', '0014_bloodrequest_stock_deducted'),
        ('blood_bank_technician', '0003_remove_blooddispatch_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddispatch',
            name='donor_blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='donor.donorbloodrequest'),
        ),
        migrations.AlterField(
            model_name='blooddispatch',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='patient.bloodrequest'),
        ),
    ]
