# Generated by Django 4.2.23 on 2026-02-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_technician', '0004_blooddispatch_donor_blood_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbanktechprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='bloodbank_profiles/'),
        ),
    ]
