"""
Django settings for Blood Connect project.
Generated by 'django-admin startproject' using Django 3.0.5.
"""

import os
from pathlib import Path

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Templates and static directories
TEMPLATE_DIR = BASE_DIR / 'templates'
STATIC_DIR = BASE_DIR / 'static'
MEDIA_DIR = BASE_DIR / 'media'

# Secret key (keep this secret in production)
SECRET_KEY = '+zy!9k=9pql5gz9bkqjore)k6r!%w0atk(@(!(!zvp5e(t2i8n'

# Debug mode (disable in production)
DEBUG = True

ALLOWED_HOSTS = []

# Installed apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'widget_tweaks',
    'django_extensions',

    # Local apps
    'blood',
    'donor',
    'patient',
    'nurse',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

CSRF_COOKIE_SECURE = False

ROOT_URLCONF = 'bloodbankmanagement.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Custom context processors
                'patient.context_processors.patient_notification_count',  
                'donor.context_processors.donor_notification_count',
                'blood.context_processors.admin_notification_counts',
                'nurse.context_processors.nurse_unread_notifications',

            ],
        },
    },
]

WSGI_APPLICATION = 'bloodbankmanagement.wsgi.application'

# Database (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bloodconnect',      # DB name
        'USER': 'allankibet',        # PostgreSQL username
        'PASSWORD': 'Bokelo@360',    # PostgreSQL password
        'HOST': 'localhost',         # DB host
        'PORT': '5432',              # Default PostgreSQL port
    }
}

# Primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC_DIR]                 # Your development static files location
STATIC_ROOT = BASE_DIR / 'staticfiles'         # Collected static files for production

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = MEDIA_DIR

# Login redirect
LOGIN_REDIRECT_URL = '/afterlogin'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'from@gmail.com'   # Replace with your sender email
EMAIL_HOST_PASSWORD = 'xyz'          # Replace with your sender password

# Email recipients
EMAIL_RECEIVING_USER = ['to@gmail.com']  # List of recipients for notifications

