"""
Django settings for Blood Connect project.
Generated by 'django-admin startproject' using Django 3.0.5.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import sys

# Load .env (local) or environment variables
load_dotenv()


# =============================
# BASE DIRECTORIES
# =============================
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = BASE_DIR / 'templates'
STATIC_DIR = BASE_DIR / 'static'
MEDIA_DIR = BASE_DIR / 'media'

# =============================
# SECURITY
# =============================
# FIXED: Remove default fallback secret key - must be set in environment
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable is not set!")

DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# =============================
# ALLOWED HOSTS
# =============================
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'blood-connect-production.up.railway.app',
    '.railway.app',  # Wildcard for all Railway subdomains
    'blood-connect-f6jb.onrender.com',
]

# Add Railway domain
RAILWAY_STATIC_URL = os.getenv('RAILWAY_STATIC_URL')
RAILWAY_PUBLIC_DOMAIN = os.getenv('RAILWAY_PUBLIC_DOMAIN')

if RAILWAY_STATIC_URL:
    # Extract domain from Railway static URL
    domain = RAILWAY_STATIC_URL.replace('https://', '').replace('http://', '').split('/')[0]
    if domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(domain)

if RAILWAY_PUBLIC_DOMAIN:
    if RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Add Render domain (for backward compatibility)
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    if RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# =============================
# INSTALLED APPS
# =============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary',
    'django.contrib.staticfiles',

    # Third-party
    'widget_tweaks',
    'django_extensions',

    # Local apps
    'blood',
    'donor',
    'patient',
    'nurse',
    'chatbot',
]

# =============================
# MIDDLEWARE
# =============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise BEFORE Django static middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =============================
# SECURITY SETTINGS
# =============================
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# Additional security headers for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# Trust Railway's proxy - MUST include https://
CSRF_TRUSTED_ORIGINS = [
    'https://blood-connect-production.up.railway.app',
]

# Add Railway domains with https://
if RAILWAY_STATIC_URL:
    if not RAILWAY_STATIC_URL.startswith('http'):
        CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_STATIC_URL}'.rstrip('/'))
    else:
        CSRF_TRUSTED_ORIGINS.append(RAILWAY_STATIC_URL.rstrip('/'))

if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')

ROOT_URLCONF = 'bloodbankmanagement.urls'

# =============================
# TEMPLATES
# =============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Custom
                'patient.context_processors.patient_notification_count',
                'donor.context_processors.donor_notification_count',
                'blood.context_processors.admin_notification_counts',
                'nurse.context_processors.nurse_unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'bloodbankmanagement.wsgi.application'

# =============================
# DATABASE (Railway, Render, or local)
# =============================
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Production - Use the DATABASE_URL from environment
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=not DEBUG  # SSL required in production
        )
    }
else:
    # Local development database
    # UPDATED: PostgreSQL configuration as requested
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'bloodconnect',
            'USER': 'allan',
            'PASSWORD': 'Bokelo@360',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# =============================
# DATABASE POOLING (for production)
# =============================
# For production environments with high traffic
if not DEBUG:
    DATABASES['default']['CONN_MAX_AGE'] = 60  # Connection reuse for 60 seconds

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================
# PASSWORD VALIDATION
# =============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =============================
# INTERNATIONALIZATION
# =============================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# =============================
# STATIC FILES
# =============================
STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC_DIR]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Conditional storage backend based on DEBUG mode
if not DEBUG:
    # Production: simpler storage to avoid manifest errors
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    # Development: manifest storage for cache-busting
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# =============================
# MEDIA FILES
# =============================
MEDIA_URL = '/media/'
MEDIA_ROOT = MEDIA_DIR

# =============================
# CLOUDINARY CONFIGURATION
# =============================
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET')
}

# Use Cloudinary for media storage in production
if not DEBUG and os.getenv('CLOUDINARY_CLOUD_NAME'):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Initialize Cloudinary if configured
if all([os.getenv('CLOUDINARY_CLOUD_NAME'), 
        os.getenv('CLOUDINARY_API_KEY'), 
        os.getenv('CLOUDINARY_API_SECRET')]):
    cloudinary.config(
        cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
        api_key=os.getenv('CLOUDINARY_API_KEY'),
        api_secret=os.getenv('CLOUDINARY_API_SECRET'),
        secure=True
    )

# =============================
# AUTHENTICATION & LOGIN CONFIGURATION
# =============================
LOGIN_URL = '/patient/patientlogin'
LOGIN_REDIRECT_URL = '/afterlogin/'
LOGOUT_REDIRECT_URL = '/'

# Session configuration
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_NAME = 'bloodconnect_sessionid'
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# =============================
# EMAIL CONFIG
# =============================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

# Use environment variables or hardcoded for local development
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'noreply@bloodconnect.com'
SERVER_EMAIL = EMAIL_HOST_USER or 'noreply@bloodconnect.com'

# Validate email configuration in production
if not DEBUG:
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning("Email credentials not configured. Email functionality will not work.")

# =============================
# CELERY CONFIGURATION
# =============================
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# =============================
# LOGGING (SECURE - NO SENSITIVE DATA)
# =============================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'secure': {
            'format': '{levelname} {asctime} {module} - {message}',
            'style': '{',
        },
    },

    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'secure',  # Changed to secure formatter
        },
        'console_debug': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'verbose',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/django_errors.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },

    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },

    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console_debug'] if DEBUG else ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'blood': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'donor': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'patient': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'nurse': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# =============================
# CUSTOM SETTINGS
# =============================
# Application-specific settings
MAX_DONATIONS_PER_DAY = 50
BLOOD_REQUEST_EXPIRY_DAYS = 7
DONOR_MIN_AGE = 18
DONOR_MAX_AGE = 65

# =============================
# STARTUP VALIDATION
# =============================
if not DEBUG:
    # Validate critical settings are configured
    required_settings = {
        'DJANGO_SECRET_KEY': SECRET_KEY,
        'DATABASE_URL': DATABASE_URL,
    }
    
    missing = [key for key, value in required_settings.items() if not value]
    if missing:
        raise ValueError(f"Missing required environment variables: {', '.join(missing)}")

# Create logs directory if it doesn't exist
LOG_DIR = BASE_DIR / 'logs'
if not LOG_DIR.exists():
    LOG_DIR.mkdir(exist_ok=True)