"""
Django settings for Blood Connect project.
Generated by 'django-admin startproject' using Django 3.0.5.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import sys
import warnings

# Load .env (local) or environment variables
load_dotenv()

# =============================
# DEBUG ENVIRONMENT VARIABLES
# =============================
print("="*60)
print("🔍 ENVIRONMENT VARIABLES DEBUG")
print("="*60)
print(f"RENDER_EXTERNAL_HOSTNAME: {os.getenv('RENDER_EXTERNAL_HOSTNAME')}")
print(f"REDIS_URL from os.getenv: {os.getenv('REDIS_URL')}")
print(f"REDIS_URL from os.environ.get: {os.environ.get('REDIS_URL')}")
print(f"All env vars containing REDIS: {[k for k in os.environ.keys() if 'REDIS' in k]}")
print(f"Current Working Directory: {os.getcwd()}")
print(f"BASE_DIR: {Path(__file__).resolve().parent.parent}")
print("="*60)
sys.stdout.flush()  # Force print to show in logs

# =============================
# BASE DIRECTORIES
# =============================
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================
# SECURITY
# =============================
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable is not set!")

DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# =============================
# ALLOWED HOSTS
# =============================
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]

# Add Render domain dynamically
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# =============================
# INSTALLED APPS
# =============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Third-party
    'widget_tweaks',
    'django_extensions',
    'django_ratelimit',  # For rate limiting honeypot
    'django_redis',  # Redis cache backend
    
    # Local apps
    'blood',
    'donor',
    'utils', 
    'phlebotomist.apps.PhlebotomistConfig',
    'chatbot',
    'hospital',
    'lab_technologist', 
    'blood_bank_technician',
]

# =============================
# MIDDLEWARE
# =============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # WhiteNoise MUST be here (right after SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =============================
# SECURITY SETTINGS
# =============================
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# Additional security headers for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# CSRF Trusted Origins for Render
CSRF_TRUSTED_ORIGINS = []

if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

ROOT_URLCONF = 'bloodbankmanagement.urls'

# =============================
# TEMPLATES
# =============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Custom
                'donor.context_processors.donor_notification_count',
                'donor.context_processors.donor_eligibility_context',
                'donor.context_processors.donor_support_options',

                'phlebotomist.context_processors.phlebotomist_unread_notifications',
                'hospital.context_processors.hospital_user_context',
                'blood.context_processors.user_role_context', 
                
            ],
        },
    },
]

WSGI_APPLICATION = 'bloodbankmanagement.wsgi.application'

# =============================
# DATABASE
# =============================
DATABASE_URL = os.getenv('DATABASE_URL')

if not DATABASE_URL:
    raise ValueError("DATABASE_URL environment variable is not set!")

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
    )
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================
# REDIS/CACHE CONFIGURATION
# =============================

# Try multiple methods to get Redis URL
print("="*60)
print("🔍 REDIS CONFIGURATION DEBUG")
print("="*60)

# Method 1: Direct from os.environ
REDIS_URL = os.environ.get('REDIS_URL')
print(f"Method 1 (os.environ.get): {REDIS_URL}")

# Method 2: From os.getenv
if not REDIS_URL:
    REDIS_URL = os.getenv('REDIS_URL')
    print(f"Method 2 (os.getenv): {REDIS_URL}")

# Method 3: Check if it's under a different name
if not REDIS_URL:
    REDIS_URL = os.getenv('REDIS_TLS_URL') or os.getenv('REDIS_INTERNAL_URL')
    print(f"Method 3 (alternate names): {REDIS_URL}")

# Method 4: Hardcode for testing (uncomment if needed)
# if not REDIS_URL:
#     REDIS_URL = 'redis://red-d6ka3g95pdvs73ckpfng:6379'
#     print(f"Method 4 (hardcoded): {REDIS_URL}")

# Final fallback to localhost
if not REDIS_URL:
    REDIS_URL = 'redis://127.0.0.1:6379/1'
    print(f"⚠️  Using fallback localhost: {REDIS_URL}")

print(f"🔥 FINAL REDIS URL: {REDIS_URL}")

# Check if we're on Render
ON_RENDER = bool(os.getenv('RENDER_EXTERNAL_HOSTNAME'))
print(f"ON_RENDER: {ON_RENDER}")

if ON_RENDER and '127.0.0.1' in REDIS_URL:
    print("❌ ERROR: On Render but still using localhost Redis!")
    print("   Please check your REDIS_URL environment variable in Render dashboard")
    print("   Expected: redis://red-d6ka3g95pdvs73ckpfng:6379")
    print("   Got: {REDIS_URL}")
    
if ON_RENDER and not os.getenv('REDIS_URL'):
    print("⚠️  WARNING: On Render but REDIS_URL not set in environment!")
    
print("="*60)
sys.stdout.flush()

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Add these for better production performance
            'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 50,  # Match your Redis instance limit
                'timeout': 20,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,  # 5 seconds
            'SOCKET_TIMEOUT': 5,  # 5 seconds
            'RETRY_ON_TIMEOUT': True,
            'IGNORE_EXCEPTIONS': True,  # Don't crash if Redis is down
        },
        'KEY_PREFIX': 'bloodconnect',  # Add prefix to avoid key collisions
        'TIMEOUT': 300,  # 5 minutes default timeout
    }
}

# Optional: Add a fallback cache for when Redis is unavailable
if ON_RENDER and not os.getenv('REDIS_URL'):
    # In production, if REDIS_URL is missing, use a dummy cache as fallback
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }

# Tell django-ratelimit which cache to use
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_ENABLE = True  # Enable rate limiting

# =============================
# PASSWORD VALIDATION
# =============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =============================
# INTERNATIONALIZATION
# =============================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# =============================
# STATIC FILES
# =============================
STATIC_URL = '/static/'

# For development: Where Django looks for static files (source files)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# For production: Where collectstatic puts files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Prevent 404 errors for missing files in production
WHITENOISE_MANIFEST_STRICT = False

# =============================
# MEDIA FILES
# =============================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================
# CLOUDINARY CONFIGURATION
# =============================
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET')
}

# Use Cloudinary for media storage in production
if not DEBUG and os.getenv('CLOUDINARY_CLOUD_NAME'):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Initialize Cloudinary if configured
if all([os.getenv('CLOUDINARY_CLOUD_NAME'), 
        os.getenv('CLOUDINARY_API_KEY'), 
        os.getenv('CLOUDINARY_API_SECRET')]):
    cloudinary.config(
        cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
        api_key=os.getenv('CLOUDINARY_API_KEY'),
        api_secret=os.getenv('CLOUDINARY_API_SECRET'),
        secure=True
    )

# =============================
# AUTHENTICATION & LOGIN CONFIGURATION
# =============================
LOGIN_URL = "/donor/donorlogin"
LOGIN_REDIRECT_URL = '/afterlogin/'
LOGOUT_REDIRECT_URL = '/'

# Session configuration
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_NAME = 'bloodconnect_sessionid'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# =============================
# EMAIL CONFIG
# =============================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'noreply@bloodconnect.com'
SERVER_EMAIL = EMAIL_HOST_USER or 'noreply@bloodconnect.com'

# Validate email configuration in production
if not DEBUG:
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning("Email credentials not configured. Email functionality will not work.")

# =============================
# ENHANCED LOGGING FOR HONEYPOT
# =============================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'honeypot': {  # Special formatter for honeypot logs
            'format': '\n🔴 HONEYPOT ATTACK - {asctime}\n   IP: {message}\n   {levelname}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'simple',
        },
        'honeypot_file': {  # Separate file for honeypot logs
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'honeypot.log',
            'formatter': 'honeypot',
        },
        'honeypot_email': {  # Email alerts for serious attempts
            'level': 'WARNING',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },

    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },

    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'blood.views': {  # Logger for honeypot views
            'handlers': ['console', 'honeypot_file', 'honeypot_email'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# =============================
# CUSTOM SETTINGS
# =============================
MAX_DONATIONS_PER_DAY = 50
BLOOD_REQUEST_EXPIRY_DAYS = 7
DONOR_MIN_AGE = 18
DONOR_MAX_AGE = 65

# =============================
# HONEYPOT SETTINGS
# =============================
HONEYPOT_ENABLED = True  # Master switch for honeypot
HONEYPOT_LOG_ALL_ATTEMPTS = True  # Log all attempts to database
HONEYPOT_EMAIL_ALERTS = True  # Send email alerts for suspicious attempts
HONEYPOT_DELAY_ATTEMPTS = True  # Add delay to slow down brute force
HONEYPOT_MAX_ATTEMPTS_PER_IP = 10  # Max attempts before special messages

# =============================
# STARTUP VALIDATION
# =============================
if not DEBUG:
    # Validate critical settings are configured
    required_settings = {
        'DJANGO_SECRET_KEY': SECRET_KEY,
        'DATABASE_URL': DATABASE_URL,
    }
    
    missing = [key for key, value in required_settings.items() if not value]
    if missing:
        raise ValueError(f"Missing required environment variables: {', '.join(missing)}")

# =============================
# DEVELOPMENT SETTINGS OVERRIDE
# =============================
if DEBUG:
    # Force static files to work in development
    import mimetypes
    mimetypes.add_type("text/css", ".css", True)
    mimetypes.add_type("text/javascript", ".js", True)

# =============================
# AUTHENTICATION BACKENDS
# =============================
AUTHENTICATION_BACKENDS = [
    'donor.authentication_backends.EmailOrUsernameBackend',  
    'django.contrib.auth.backends.ModelBackend',
]

# =============================
# SESSION SETTINGS
# =============================
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = True

# =============================
# LOGIN SETTINGS
# =============================
LOGIN_URL = 'donor:donorlogin'
LOGIN_REDIRECT_URL = 'donor:donor-dashboard'
LOGOUT_REDIRECT_URL = 'home'

ADMIN_SECRET_URL = os.getenv('ADMIN_SECRET_URL', 'dev-admin-only')

# Final debug print
print("="*60)
print("✅ Settings.py loaded completely")
print("="*60)
sys.stdout.flush()