# Generated by Django 4.2.23 on 2026-02-28 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('blood', '0002_initial'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phlebotomist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='phlebotomist_profiles/')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualification', models.CharField(blank=True, help_text='Phlebotomist qualification/degree', max_length=200)),
                ('specialization', models.CharField(blank=True, help_text='E.g., Blood Bank, Emergency, ICU', max_length=100)),
                ('license_expiry', models.DateField(blank=True, help_text='License expiration date', null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether phlebotomist account is approved by admin')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_phlebotomists', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phlebotomists', to='blood.donationcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phlebotomist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phlebotomist',
                'verbose_name_plural': 'phlebotomists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donationcenter')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
                ('phlebotomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phlebotomist.phlebotomist')),
                ('request_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='phlebotomist',
            index=models.Index(fields=['center', 'is_active'], name='phlebotomis_center__d29f39_idx'),
        ),
        migrations.AddIndex(
            model_name='phlebotomist',
            index=models.Index(fields=['license_expiry'], name='phlebotomis_license_d2f5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='phlebotomist',
            index=models.Index(fields=['is_approved'], name='phlebotomis_is_appr_eea0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='phlebotomist',
            index=models.Index(fields=['specialization'], name='phlebotomis_special_81c405_idx'),
        ),
        migrations.AddConstraint(
            model_name='phlebotomist',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_phlebotomist_user'),
        ),
        migrations.AddConstraint(
            model_name='phlebotomist',
            constraint=models.UniqueConstraint(fields=('license_number',), name='unique_phlebotomist_license'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['request_content_type', 'request_object_id'], name='phlebotomis_request_2990d2_idx'),
        ),
    ]
