# Generated by Django 4.2.23 on 2026-03-01 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('donor', '0003_alter_blooddonate_date_alter_blooddonate_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0003_initial'),
        ('phlebotomist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changed_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='center',
            field=models.ForeignKey(help_text='Donation center where appointment takes place', on_delete=django.db.models.deletion.CASCADE, to='blood.donationcenter'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(help_text='Appointment date and time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='donor',
            field=models.ForeignKey(blank=True, help_text='Donor associated with this appointment (for blood donations)', null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments about the appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phlebotomist',
            field=models.ForeignKey(help_text='Phlebotomist assigned to this appointment', on_delete=django.db.models.deletion.CASCADE, to='phlebotomist.phlebotomist'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request_content_type',
            field=models.ForeignKey(blank=True, help_text='Content type of the related object (e.g., BloodDonate)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('collected', 'Sample Collected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the appointment', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['donor', 'status'], name='phlebotomis_donor_i_3fd292_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['phlebotomist', 'status'], name='phlebotomis_phlebot_e11e85_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['center', 'date'], name='phlebotomis_center__049e16_idx'),
        ),
    ]
