# Generated by Django 4.2.23 on 2026-03-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlebotomist', '0002_alter_appointment_options_appointment_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved_by_role',
            field=models.CharField(blank=True, choices=[('phlebotomist', 'Phlebotomist'), ('system', 'System'), ('admin', 'Admin')], help_text='Role of the user who approved this appointment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='barcode',
            field=models.CharField(blank=True, help_text='Blood bag barcode assigned to this donation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by_role',
            field=models.CharField(blank=True, choices=[('phlebotomist', 'Phlebotomist'), ('donor', 'Donor'), ('system', 'System'), ('admin', 'Admin')], help_text='Role of the user who cancelled this appointment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='collected_by_role',
            field=models.CharField(blank=True, choices=[('phlebotomist', 'Phlebotomist'), ('system', 'System'), ('admin', 'Admin')], help_text='Role of the user who collected this blood sample', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_by_role',
            field=models.CharField(blank=True, choices=[('phlebotomist', 'Phlebotomist'), ('system', 'System'), ('admin', 'Admin')], help_text='Role of the user who rejected this appointment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sent_to_lab_at',
            field=models.DateTimeField(blank=True, help_text='When this sample was sent to the lab for testing', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_changed_by_role',
            field=models.CharField(blank=True, choices=[('phlebotomist', 'Phlebotomist'), ('lab_tech', 'Lab Technologist'), ('blood_bank_tech', 'Blood Bank Technician'), ('donor', 'Donor'), ('system', 'System'), ('admin', 'Admin')], help_text='Role of the user who last changed the status', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['barcode'], name='phlebotomis_barcode_9c7340_idx'),
        ),
    ]
