# Generated by Django 4.2.23 on 2025-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_emergency_contact_patient_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
