# Generated by Django 4.2.23 on 2025-10-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0019_alter_stocktransaction_blood_request_and_more'),
        ('patient', '0006_bloodrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blood Request', 'verbose_name_plural': 'Blood Requests'},
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='first_name',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='last_name',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text="Patient's blood group", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='contact_number',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
         model_name='bloodrequest',
         name='donation_center',
         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blood.donationcenter'),
         preserve_default=False,
        ),

        migrations.AlterField(
            model_name='bloodrequest',
            name='unit',
            field=models.PositiveIntegerField(blank=True, help_text='Required blood volume in ml (450-2700)', null=True),
        ),
    ]
