# Generated by Django 4.2.23 on 2025-11-03 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0008_patient_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodgroup_verified',
            field=models.BooleanField(default=False, help_text='Blood group verified by nurse on first blood request'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodgroup_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodgroup_verified_by',
            field=models.ForeignKey(blank=True, help_text='Nurse who verified the blood group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_patient_bloodgroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
