# Generated by Django 4.2.23 on 2025-11-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_patient_bloodgroup_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='urgency_level',
        ),
    ]
