# Generated by Django 4.2.23 on 2026-02-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_technician', '0003_remove_blooddispatch_inventory_item_and_more'),
        ('blood', '0026_alter_stockunit_barcode_bloodbagbarcode_and_more'),
        ('patient', '0010_remove_bloodrequest_urgency_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='approved_at_nurse',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='cancelled_at',
            new_name='dispatched_at',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='cancellation_reason',
            new_name='rejected_reason',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='completed_at_nurse',
            new_name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='approved_by_nurse',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='completed_by_nurse',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='stock_deducted',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_patient_requests', to='blood_bank_technician.bloodbanktechprofile'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_patient_requests', to='blood_bank_technician.bloodbanktechprofile'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_patient_requests', to='blood_bank_technician.bloodbanktechprofile'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', help_text='Blood group needed', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='donation_center',
            field=models.ForeignKey(help_text='Blood bank center to fulfill this request', on_delete=django.db.models.deletion.CASCADE, to='blood.donationcenter'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Ready for Pickup'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='unit',
            field=models.PositiveIntegerField(default='1 unit', help_text='Required blood volume in ml (450-2700)'),
            preserve_default=False,
        ),
    ]
