# Generated by Django 4.2.23 on 2026-02-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_rename_approved_at_nurse_bloodrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
