# Generated by Django 4.2.23 on 2026-02-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
