# Generated by Django 4.2.23 on 2026-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_bloodrequest_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
