# Generated by Django 4.2.23 on 2026-02-27 15:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('banner_type', models.CharField(choices=[('info', 'Information'), ('urgent', 'Urgent'), ('success', 'Success Story'), ('event', 'Event')], default='info', max_length=20)),
                ('link_text', models.CharField(blank=True, help_text='Button text (optional)', max_length=50)),
                ('link_url', models.URLField(blank=True, help_text='Button link (optional)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodBagBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bag_type', models.CharField(choices=[('single', 'Single Blood Bag'), ('double', 'Double Blood Bag'), ('triple', 'Triple Blood Bag'), ('pediatric', 'Pediatric Blood Bag')], default='single', max_length=20)),
                ('volume_ml', models.IntegerField(default=450, help_text='Standard volume in ml')),
                ('anticoagulant', models.CharField(choices=[('cpd', 'CPD (Citrate Phosphate Dextrose)'), ('cpda1', 'CPDA-1'), ('sagm', 'SAG-Mannitol')], default='cpd', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned to Donor'), ('collected', 'Blood Collected'), ('tested', 'Tested'), ('discarded', 'Discarded')], default='available', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodDriveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blood_drives/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('location', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('event_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name': 'Blood Drive Event',
                'verbose_name_plural': 'Blood Drive Events',
                'ordering': ['display_order', '-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_read', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sender_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyFactChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_participants', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Fact Challenge',
                'verbose_name_plural': 'Daily Fact Challenges',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DonationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('open_hours', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationFunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('blood', 'Blood Science & Biology'), ('donation', 'Donation Process & Impact'), ('health', 'Health Benefits'), ('myths', 'Myth Busters'), ('fun', 'Fun Facts & History'), ('local', 'Kenyan Context')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('fact_text', models.TextField()),
                ('image_url', models.CharField(blank=True, help_text='URL to an image (can be Unsplash, Pexels, etc.)', max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('has_quiz', models.BooleanField(default=False)),
                ('quiz_question', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_answer_1', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_answer_2', models.CharField(blank=True, max_length=200, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('times_viewed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation Fun Fact',
                'verbose_name_plural': 'Donation Fun Facts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('blood', 'Blood Science & Biology'), ('donation', 'Donation Process & Impact'), ('health', 'Health Benefits'), ('myths', 'Myth Busters'), ('fun', 'Fun Facts & History'), ('local', 'Kenyan Context')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('fact_text', models.TextField()),
                ('source', models.URLField(blank=True, help_text='Source URL for verification', null=True)),
                ('has_quiz', models.BooleanField(default=False)),
                ('quiz_question', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_answer_1', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_answer_2', models.CharField(blank=True, max_length=200, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(help_text="e.g., 'Active Donors'", max_length=100)),
                ('stat_value', models.IntegerField()),
                ('icon_class', models.CharField(default='fas fa-users', help_text="Font Awesome class (e.g., 'fas fa-users')", max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Stat',
                'verbose_name_plural': 'Homepage Stats',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('unit', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_deducted', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_added', models.PositiveIntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('deduction', 'Deduction'), ('addition', 'Addition')], max_length=20)),
                ('transaction_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transaction', null=True)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-transaction_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text="e.g., 'Blood Donor', 'Patient', 'Nurse'", max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('testimonial', models.TextField(max_length=800)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFactInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('like', 'Liked'), ('share', 'Shared'), ('quiz_attempt', 'Quiz Attempted'), ('quiz_correct', 'Quiz Correct'), ('quiz_wrong', 'Quiz Wrong')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donationfunfact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Fact Interaction',
                'verbose_name_plural': 'User Fact Interactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('barcode', models.CharField(help_text='Barcode from pre-generated blood bag', max_length=100, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('safety_status', models.CharField(choices=[('pending', 'Pending Verification'), ('safe', 'Safe for Use'), ('unsafe', 'Unsafe - Do Not Use')], default='pending', help_text='Safety verification status of this blood unit', max_length=20)),
                ('safety_verified_by_role', models.CharField(blank=True, choices=[('nurse', 'Nurse'), ('lab_tech', 'Lab Technologist'), ('system', 'System')], help_text='Role of the person who verified safety', max_length=20, null=True)),
                ('safety_verified_at', models.DateTimeField(blank=True, help_text='When the safety verification was done', null=True)),
                ('safety_notes', models.TextField(blank=True, help_text='Notes about safety verification (e.g., test results, issues found)', null=True)),
                ('unsafe_reason', models.CharField(blank=True, choices=[('contamination', 'Contamination Detected'), ('disease_markers', 'Disease Markers Present'), ('quality_issues', 'Quality Issues'), ('improper_storage', 'Improper Storage'), ('expired', 'Expired'), ('other', 'Other Reason')], help_text='Reason why blood is marked unsafe', max_length=100, null=True)),
                ('is_quarantined', models.BooleanField(default=False, help_text='Whether this unit is quarantined and cannot be used')),
                ('added_to_inventory_by_role', models.CharField(blank=True, choices=[('nurse', 'Nurse'), ('lab_tech', 'Lab Technologist'), ('system', 'System')], default='nurse', help_text='Role of the person who added to inventory', max_length=20, null=True)),
                ('added_to_inventory_at', models.DateTimeField(auto_now_add=True, help_text='When this was added to inventory', null=True)),
                ('added_to_inventory_by', models.ForeignKey(blank=True, help_text='User who added this to inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_stock_units', to=settings.AUTH_USER_MODEL)),
                ('blood_bag_barcode', models.OneToOneField(blank=True, help_text='The pre-generated blood bag barcode used for this donation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_unit', to='blood.bloodbagbarcode')),
            ],
            options={
                'verbose_name': 'Stock Unit',
                'verbose_name_plural': 'Stock Units',
                'ordering': ['-added_on'],
            },
        ),
    ]
