# Generated by Django 4.2.23 on 2026-02-28 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0001_initial'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockunit',
            name='blood_donation',
            field=models.ForeignKey(blank=True, help_text='Blood donation that produced this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_units', to='donor.blooddonate'),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donationcenter'),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='safety_verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified the safety status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stock_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
