# Generated by Django 4.2.23 on 2026-02-27 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('blood', '0002_initial'),
        ('nurse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.appointment'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='stockunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.stockunit'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donationcenter'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factcontribution',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_facts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factcontribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='donationcenter',
            unique_together={('name', 'city')},
        ),
        migrations.AddField(
            model_name='dailyfactchallenge',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donationfunfact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='recipient_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sender_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bloodbagbarcode',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_barcodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodbagbarcode',
            name='assigned_to_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_barcodes', to='donor.donor'),
        ),
        migrations.AddField(
            model_name='bloodbagbarcode',
            name='blood_donation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_bag_barcode', to='donor.blooddonate'),
        ),
        migrations.AddField(
            model_name='bloodbagbarcode',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_barcodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodbagbarcode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_barcodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stockunit',
            unique_together={('center', 'barcode')},
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('quantity_added__isnull', False), ('quantity_deducted__isnull', True), ('transaction_type', 'addition')), models.Q(('quantity_added__isnull', True), ('quantity_deducted__isnull', False), ('transaction_type', 'deduction')), _connector='OR'), name='quantity_matches_transaction_type'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('center', 'bloodgroup')},
        ),
        migrations.AddIndex(
            model_name='bloodbagbarcode',
            index=models.Index(fields=['barcode'], name='blood_blood_barcode_9edcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbagbarcode',
            index=models.Index(fields=['status'], name='blood_blood_status_7b6be5_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbagbarcode',
            index=models.Index(fields=['assigned_to_donor'], name='blood_blood_assigne_ae011d_idx'),
        ),
    ]
