# Generated by Django 4.2.23 on 2025-08-09 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood', '0002_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='request_by_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='patient.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('center', 'bloodgroup')},
        ),
    ]
