# Generated by Django 4.2.23 on 2026-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Honeypot Attempt',
                'verbose_name_plural': 'Honeypot Attempts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
