# Generated by Django 4.2.23 on 2025-08-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='expiry_date',
        ),
    ]
