# Generated by Django 4.2.23 on 2025-08-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_remove_stock_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
