# Generated by Django 4.2.23 on 2026-03-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_honeypotattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbagbarcode',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='bloodbagbarcode',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='bloodbagbarcode',
            name='manufacture_date',
        ),
        migrations.RemoveField(
            model_name='bloodbagbarcode',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='stockunit',
            name='component_type',
            field=models.CharField(choices=[('whole_blood', '🩸 Whole Blood (35 days)'), ('rbc', '🔴 Packed Red Blood Cells (42 days)'), ('platelets', '🟡 Platelets (5 days)'), ('ffp', '❄️ Fresh Frozen Plasma (1 year)'), ('cryo', '🧊 Cryoprecipitate (1 year)')], default='whole_blood', help_text='Type of blood component - determines expiry period', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodbagbarcode',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned to Donor'), ('collected', 'Blood Collected'), ('tested', 'Tested - Safe'), ('discarded', 'Discarded - Unsafe')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockunit',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='When the blood expires. NULL for unsafe/discarded blood.', null=True),
        ),
        migrations.AlterField(
            model_name='stockunit',
            name='unsafe_reason',
            field=models.CharField(blank=True, choices=[('hiv_positive', 'HIV Positive'), ('hepatitis_b_positive', 'Hepatitis B Positive'), ('hepatitis_c_positive', 'Hepatitis C Positive'), ('syphilis_positive', 'Syphilis Positive'), ('malaria_positive', 'Malaria Positive'), ('multiple_markers', 'Multiple Disease Markers'), ('contamination', 'Bacterial Contamination'), ('hemolysis', 'Hemolysis Detected'), ('lipemic', 'Lipemic Sample'), ('improper_storage', 'Improper Storage'), ('expired', 'Expired'), ('other', 'Other Reason')], help_text='Reason why blood is marked unsafe', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='stockunit',
            index=models.Index(fields=['expiry_date'], name='blood_stock_expiry__411eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockunit',
            index=models.Index(fields=['safety_status'], name='blood_stock_safety__1cbf73_idx'),
        ),
        migrations.AddIndex(
            model_name='stockunit',
            index=models.Index(fields=['bloodgroup'], name='blood_stock_bloodgr_11e56a_idx'),
        ),
    ]
