# Generated by Django 4.2.23 on 2026-03-05 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0005_remove_bloodbagbarcode_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='factcontribution',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='factcontribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfactinteraction',
            name='fact',
        ),
        migrations.RemoveField(
            model_name='userfactinteraction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.DeleteModel(
            name='DailyFactChallenge',
        ),
        migrations.DeleteModel(
            name='DonationFunFact',
        ),
        migrations.DeleteModel(
            name='FactContribution',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='UserFactInteraction',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_testimonial', to='blood.userreview'),
        ),
    ]
