# Generated by Django 4.2.23 on 2026-03-05 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0006_userreview_delete_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.IntegerField(blank=True, choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Unsatisfied'), (1, 'Very Unsatisfied')], null=True)),
                ('favorite_features', models.JSONField(blank=True, default=list)),
                ('recommend', models.IntegerField(blank=True, choices=[(1, 'Yes, definitely!'), (0, 'Maybe'), (-1, 'Not yet')], null=True)),
                ('improvement', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review Survey',
                'verbose_name_plural': 'Review Surveys',
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userreview',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_review'),
        ),
        migrations.AddField(
            model_name='reviewsurvey',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='blood.userreview'),
        ),
    ]
