# Generated by Django 4.2.23 on 2025-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_alter_bloodrequest_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='unit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
