# Generated by Django 4.2.23 on 2025-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_alter_bloodrequest_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='approved_bloodgroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group confirmed/updated by nurse', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='approved_units',
            field=models.PositiveIntegerField(blank=True, help_text='Units confirmed/updated by nurse', null=True),
        ),
    ]
