# Generated by Django 4.2.23 on 2025-08-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_bloodrequest_approved_bloodgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='approved_bloodgroup',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='approved_units',
        ),
    ]
