# Generated by Django 4.2.23 on 2025-08-25 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0012_nursebloodrequeststockunit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0010_remove_bloodrequest_approved_bloodgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_deducted', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_added', models.PositiveIntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('deduction', 'Deduction'), ('addition', 'Addition')], max_length=20)),
                ('transaction_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.appointment')),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.bloodrequest')),
                ('stockunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.stockunit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-transaction_at'],
            },
        ),
    ]
