# Generated by Django 4.2.23 on 2025-09-04 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_remove_blooddonate_disease_remove_blooddonate_notes'),
        ('nurse', '0014_alter_nurse_specialization'),
        ('patient', '0003_patient_emergency_contact_patient_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0012_notification_action_notification_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_donor',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_by_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='patient.patient'),
        ),
        migrations.CreateModel(
            name='DonorBloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.PositiveIntegerField()),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('unit', models.PositiveIntegerField(default=450, help_text='Requested amount in ml')),
                ('urgency_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=20)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_seen', models.BooleanField(default=False)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at_admin', models.DateTimeField(blank=True, null=True)),
                ('approved_at_nurse', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=20, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=20, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at_admin', models.DateTimeField(blank=True, null=True)),
                ('completed_at_nurse', models.DateTimeField(blank=True, null=True)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_donor_patient_requests_admin', to=settings.AUTH_USER_MODEL)),
                ('approved_by_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_donor_patient_requests_nurse', to='nurse.nurse')),
                ('completed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_donor_patient_requests_admin', to=settings.AUTH_USER_MODEL)),
                ('completed_by_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_donor_patient_requests_nurse', to='nurse.nurse')),
                ('donation_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.donationcenter')),
                ('request_by_donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_patient_requests', to='donor.donor')),
            ],
        ),
    ]
