# Generated by Django 4.2.23 on 2025-09-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0013_remove_bloodrequest_request_by_donor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='approved_at_admin',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='approved_by_admin',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='completed_at_admin',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='completed_by_admin',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='approved_at_admin',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='approved_by_admin',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='completed_at_admin',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='completed_by_admin',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorbloodrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
