# Generated by Django 4.2.23 on 2025-09-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0014_remove_bloodrequest_approved_at_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='donor_blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.donorbloodrequest'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the transaction', null=True),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('quantity_added__isnull', False), ('quantity_deducted__isnull', True), ('transaction_type', 'addition')), models.Q(('quantity_added__isnull', True), ('quantity_deducted__isnull', False), ('transaction_type', 'deduction')), _connector='OR'), name='quantity_matches_transaction_type'),
        ),
    ]
