# Generated by Django 4.2.23 on 2025-10-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0015_stocktransaction_donor_blood_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='approved_by_nurse',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='completed_by_nurse',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='donation_center',
        ),
        migrations.RemoveField(
            model_name='donorbloodrequest',
            name='request_by_donor',
        ),
    ]
