# Generated by Django 4.2.23 on 2025-10-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0016_remove_donorbloodrequest_approved_by_nurse_and_more'),
        ('donor', '0015_donorbloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='donor_blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donorbloodrequest'),
        ),
        migrations.DeleteModel(
            name='DonorBloodRequest',
        ),
    ]
