# Generated by Django 4.2.23 on 2025-10-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0017_alter_stocktransaction_donor_blood_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='approved_by_nurse',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='completed_by_nurse',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='donation_center',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_patient',
        ),
    ]
