# Generated by Django 4.2.23 on 2025-10-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_bloodrequest'),
        ('blood', '0018_remove_bloodrequest_approved_by_nurse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.bloodrequest'),
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
