# Generated by Django 4.2.23 on 2025-11-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0019_alter_stocktransaction_blood_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcenter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
