# Generated by Django 4.2.23 on 2025-12-27 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0020_donationcenter_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockunit',
            options={'ordering': ['-added_on'], 'verbose_name': 'Stock Unit', 'verbose_name_plural': 'Stock Units'},
        ),
        migrations.AddField(
            model_name='stockunit',
            name='is_quarantined',
            field=models.BooleanField(default=False, help_text='Whether this unit is quarantined and cannot be used'),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='safety_notes',
            field=models.TextField(blank=True, help_text='Notes about safety verification (e.g., test results, issues found)', null=True),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='safety_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('safe', 'Safe for Use'), ('unsafe', 'Unsafe - Do Not Use')], default='pending', help_text='Safety verification status of this blood unit', max_length=20),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='safety_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the safety verification was done', null=True),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='safety_verified_by',
            field=models.ForeignKey(blank=True, help_text='Nurse who verified the safety status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stock_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='unsafe_reason',
            field=models.CharField(blank=True, choices=[('contamination', 'Contamination Detected'), ('disease_markers', 'Disease Markers Present'), ('quality_issues', 'Quality Issues'), ('improper_storage', 'Improper Storage'), ('expired', 'Expired'), ('other', 'Other Reason')], help_text='Reason why blood is marked unsafe', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockunit',
            unique_together={('center', 'barcode')},
        ),
    ]
