# Generated by Django 4.2.23 on 2026-02-04 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0022_banner_blooddriveevent_homepagestats_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationFunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('blood', 'Blood Facts'), ('donation', 'Donation Process'), ('health', 'Health Benefits'), ('myths', 'Myth Busters'), ('impact', 'Life Impact'), ('fun', 'Fun Trivia')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('fact_text', models.TextField()),
                ('image_url', models.CharField(blank=True, help_text='URL to an image (can be Unsplash, Pexels, etc.)', max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('has_quiz', models.BooleanField(default=False)),
                ('quiz_question', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_answer_1', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_answer_2', models.CharField(blank=True, max_length=200, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('times_viewed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFactInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('like', 'Liked'), ('share', 'Shared'), ('quiz_attempt', 'Quiz Attempted'), ('quiz_correct', 'Quiz Correct'), ('quiz_wrong', 'Quiz Wrong')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donationfunfact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyFactChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_participants', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donationfunfact')),
            ],
        ),
    ]
