# Generated by Django 4.2.23 on 2026-02-04 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0023_donationfunfact_userfactinteraction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyfactchallenge',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Fact Challenge', 'verbose_name_plural': 'Daily Fact Challenges'},
        ),
        migrations.AlterModelOptions(
            name='donationfunfact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation Fun Fact', 'verbose_name_plural': 'Donation Fun Facts'},
        ),
        migrations.AlterModelOptions(
            name='userfactinteraction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Fact Interaction', 'verbose_name_plural': 'User Fact Interactions'},
        ),
        migrations.AddField(
            model_name='donationfunfact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donationfunfact',
            name='category',
            field=models.CharField(choices=[('blood', 'Blood Science & Biology'), ('donation', 'Donation Process & Impact'), ('health', 'Health Benefits'), ('myths', 'Myth Busters'), ('fun', 'Fun Facts & History'), ('local', 'Kenyan Context')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('blood', 'Blood Science & Biology'), ('donation', 'Donation Process & Impact'), ('health', 'Health Benefits'), ('myths', 'Myth Busters'), ('fun', 'Fun Facts & History'), ('local', 'Kenyan Context')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('fact_text', models.TextField()),
                ('source', models.URLField(blank=True, help_text='Source URL for verification', null=True)),
                ('has_quiz', models.BooleanField(default=False)),
                ('quiz_question', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_answer_1', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_answer_2', models.CharField(blank=True, max_length=200, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_facts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
