# Generated by Django 4.2.23 on 2026-02-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0020_remove_donorbloodrequest_urgency_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0024_alter_dailyfactchallenge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockunit',
            name='added_to_inventory_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this was added to inventory', null=True),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='added_to_inventory_by',
            field=models.ForeignKey(blank=True, help_text='User who added this to inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_stock_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='added_to_inventory_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse'), ('lab_tech', 'Lab Technologist'), ('system', 'System')], default='nurse', help_text='Role of the person who added to inventory', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='blood_donation',
            field=models.ForeignKey(blank=True, help_text='Blood donation that produced this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_units', to='donor.blooddonate'),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='safety_verified_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse'), ('lab_tech', 'Lab Technologist'), ('system', 'System')], help_text='Role of the person who verified safety', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockunit',
            name='safety_verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified the safety status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stock_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
