# Generated by Django 4.2.23 on 2026-02-25 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0020_remove_donorbloodrequest_urgency_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0025_stockunit_added_to_inventory_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockunit',
            name='barcode',
            field=models.CharField(default='MIGRATED-', help_text='Barcode from pre-generated blood bag', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BloodBagBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bag_type', models.CharField(choices=[('single', 'Single Blood Bag'), ('double', 'Double Blood Bag'), ('triple', 'Triple Blood Bag'), ('pediatric', 'Pediatric Blood Bag')], default='single', max_length=20)),
                ('volume_ml', models.IntegerField(default=450, help_text='Standard volume in ml')),
                ('anticoagulant', models.CharField(choices=[('cpd', 'CPD (Citrate Phosphate Dextrose)'), ('cpda1', 'CPDA-1'), ('sagm', 'SAG-Mannitol')], default='cpd', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned to Donor'), ('collected', 'Blood Collected'), ('tested', 'Tested'), ('discarded', 'Discarded')], default='available', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_barcodes', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_barcodes', to='donor.donor')),
                ('blood_donation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_bag_barcode', to='donor.blooddonate')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_barcodes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_barcodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockunit',
            name='blood_bag_barcode',
            field=models.OneToOneField(blank=True, help_text='The pre-generated blood bag barcode used for this donation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_unit', to='blood.bloodbagbarcode'),
        ),
        migrations.AddIndex(
            model_name='bloodbagbarcode',
            index=models.Index(fields=['barcode'], name='blood_blood_barcode_9edcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbagbarcode',
            index=models.Index(fields=['status'], name='blood_blood_status_7b6be5_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbagbarcode',
            index=models.Index(fields=['assigned_to_donor'], name='blood_blood_assigne_ae011d_idx'),
        ),
    ]
