# Generated by Django 4.2.23 on 2026-02-28 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0001_initial'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='labtech_profiles/')),
                ('phone', models.CharField(max_length=15)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.CharField(blank=True, help_text='E.g., Hematology, Microbiology, Immunology', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('certification_expiry', models.DateField(blank=True, null=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_technologists', to='blood.donationcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tech_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Technologist',
                'verbose_name_plural': 'Lab Technologists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('hiv', models.BooleanField(blank=True, null=True, verbose_name='HIV')),
                ('hepatitis_b', models.BooleanField(blank=True, null=True, verbose_name='Hepatitis B')),
                ('hepatitis_c', models.BooleanField(blank=True, null=True, verbose_name='Hepatitis C')),
                ('syphilis', models.BooleanField(blank=True, null=True, verbose_name='Syphilis')),
                ('malaria', models.BooleanField(blank=True, null=True, verbose_name='Malaria')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('safe', 'Safe'), ('unsafe', 'Unsafe')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('blood_collection', models.OneToOneField(limit_choices_to={'status': 'collected'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_test', to='donor.blooddonate')),
                ('tested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_performed', to='lab_technologist.labtechnologistprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='labtechnologistprofile',
            index=models.Index(fields=['center', 'is_active'], name='lab_technol_center__d0a174_idx'),
        ),
        migrations.AddIndex(
            model_name='labtechnologistprofile',
            index=models.Index(fields=['specialization'], name='lab_technol_special_628476_idx'),
        ),
        migrations.AddIndex(
            model_name='labtechnologistprofile',
            index=models.Index(fields=['certification_expiry'], name='lab_technol_certifi_43216d_idx'),
        ),
        migrations.AddConstraint(
            model_name='labtechnologistprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_labtech_user'),
        ),
        migrations.AddConstraint(
            model_name='labtechnologistprofile',
            constraint=models.UniqueConstraint(fields=('employee_id',), name='unique_labtech_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='labtechnologistprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('license_number__isnull', False), models.Q(('license_number', ''), _negated=True)), fields=('license_number',), name='unique_labtech_license'),
        ),
    ]
