# Generated by Django 4.2.23 on 2026-02-27 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_initial'),
        ('lab_technologist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='certification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='certification_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='E.g., Hematology, Microbiology, Immunology', max_length=100),
        ),
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='labtechnologistprofile',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_technologists', to='blood.donationcenter'),
        ),
        migrations.AlterField(
            model_name='labtechnologistprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 27, 19, 23, 59, 99691, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labtechnologistprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 2, 27, 19, 24, 11, 787270, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='labtechnologistprofile',
            index=models.Index(fields=['center', 'is_active'], name='lab_technol_center__d0a174_idx'),
        ),
        migrations.AddIndex(
            model_name='labtechnologistprofile',
            index=models.Index(fields=['specialization'], name='lab_technol_special_628476_idx'),
        ),
        migrations.AddIndex(
            model_name='labtechnologistprofile',
            index=models.Index(fields=['certification_expiry'], name='lab_technol_certifi_43216d_idx'),
        ),
        migrations.AddConstraint(
            model_name='labtechnologistprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_labtech_user'),
        ),
        migrations.AddConstraint(
            model_name='labtechnologistprofile',
            constraint=models.UniqueConstraint(fields=('employee_id',), name='unique_labtech_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='labtechnologistprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('license_number__isnull', False), models.Q(('license_number', ''), _negated=True)), fields=('license_number',), name='unique_labtech_license'),
        ),
    ]
