# Generated by Django 4.2.23 on 2026-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_technologist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
