# Generated by Django 4.2.23 on 2026-03-05 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab_technologist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin approved this technologist', null=True),
        ),
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this technologist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lab_techs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether admin has approved this lab technologist'),
        ),
        migrations.AddIndex(
            model_name='labtechnologistprofile',
            index=models.Index(fields=['is_approved'], name='lab_technol_is_appr_6275f0_idx'),
        ),
    ]
