# Generated by Django 4.2.23 on 2026-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_technologist', '0002_labtechnologistprofile_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtechnologistprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lab Technologist', 'verbose_name_plural': 'Lab Technologists'},
        ),
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
