# Generated by Django 4.2.23 on 2026-02-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_technologist', '0003_alter_labtechnologistprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnologistprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='labtech_profiles/'),
        ),
    ]
