# Generated by Django 4.2.23 on 2026-02-27 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nurse', 'verbose_name_plural': 'Nurses'},
        ),
        migrations.AddField(
            model_name='nurse',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nurses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurse',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether nurse account is approved by admin'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='license_expiry',
            field=models.DateField(blank=True, help_text='License expiration date', null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='qualification',
            field=models.CharField(blank=True, help_text='Nursing qualification/degree', max_length=200),
        ),
        migrations.AddField(
            model_name='nurse',
            name='specialization',
            field=models.CharField(blank=True, help_text='E.g., Blood Bank, Emergency, ICU', max_length=100),
        ),
        migrations.AddField(
            model_name='nurse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurses', to='blood.donationcenter'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['center', 'is_active'], name='nurse_nurse_center__04b28e_idx'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['license_expiry'], name='nurse_nurse_license_9108a7_idx'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['is_approved'], name='nurse_nurse_is_appr_1a6894_idx'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['specialization'], name='nurse_nurse_special_8e92b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='nurse',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_nurse_user'),
        ),
        migrations.AddConstraint(
            model_name='nurse',
            constraint=models.UniqueConstraint(fields=('license_number',), name='unique_nurse_license'),
        ),
    ]
