# Generated by Django 4.2.23 on 2025-08-09 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_remove_stock_expiry_date'),
        ('nurse', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='donation_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurses', to='blood.donationcenter'),
        ),
        migrations.AlterField(
            model_name='nursebloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
