# Generated by Django 4.2.23 on 2025-08-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_alter_nurse_donation_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('nurse', 'Nurse'), ('patient', 'Patient'), ('system', 'System'), ('unknown', 'Unknown')], max_length=10, null=True),
        ),
    ]
