# Generated by Django 4.2.23 on 2025-08-11 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nurse', '0004_appointment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_cancelled', to=settings.AUTH_USER_MODEL),
        ),
    ]
