# Generated by Django 4.2.23 on 2025-08-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0005_appointment_cancelled_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='registration_number',
            field=models.CharField(default='TEMP_REG_NUM', help_text='Official nurse registration/license number', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nurse',
            name='specialization',
            field=models.CharField(choices=[('blood_bank', 'Blood Bank Nursing'), ('transfusion', 'Transfusion Nursing'), ('hematology', 'Hematology Nursing'), ('phlebotomy', 'Phlebotomy Specialist'), ('clinical_blood_nurse', 'Clinical Nurse Specialist (Blood Bank)')], default='blood_bank', help_text='Select specialization relevant to blood donation', max_length=50),
            preserve_default=False,
        ),
    ]
