# Generated by Django 4.2.23 on 2025-08-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0007_appointment_approved_at_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='nurse_profiles/'),
        ),
    ]
