# Generated by Django 4.2.23 on 2025-08-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_bloodrequest_approved_at_admin_and_more'),
        ('nurse', '0008_alter_nurse_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nursebloodrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nurse Blood Request', 'verbose_name_plural': 'Nurse Blood Requests'},
        ),
        migrations.AlterField(
            model_name='nursebloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group requested.', max_length=3),
        ),
        migrations.AlterField(
            model_name='nursebloodrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason or notes for this blood request.', null=True),
        ),
        migrations.AlterField(
            model_name='nursebloodrequest',
            name='requester',
            field=models.ForeignKey(help_text='Nurse who made the blood request.', on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests_made', to='nurse.nurse'),
        ),
        migrations.AlterField(
            model_name='nursebloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', help_text='Current status of the blood request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='nursebloodrequest',
            name='supplying_center',
            field=models.ForeignKey(help_text='Donation center supplying the requested blood.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_requests', to='blood.donationcenter'),
        ),
        migrations.AlterField(
            model_name='nursebloodrequest',
            name='units',
            field=models.PositiveIntegerField(help_text='Quantity of blood requested in milliliters.'),
        ),
    ]
