# Generated by Django 4.2.23 on 2025-08-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0009_alter_nursebloodrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursebloodrequest',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Indicate the urgency of this blood request.', max_length=10),
        ),
    ]
