# Generated by Django 4.2.23 on 2025-08-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0010_nursebloodrequest_urgency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursebloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the blood request.', max_length=20),
        ),
    ]
