# Generated by Django 4.2.23 on 2025-08-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_bloodrequest_approved_at_admin_and_more'),
        ('nurse', '0011_alter_nursebloodrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseBloodRequestStockUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_used', models.PositiveIntegerField(help_text='Amount of blood (ml) used from this stock unit.')),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nursebloodrequest')),
                ('stock_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.stockunit')),
            ],
            options={
                'unique_together': {('blood_request', 'stock_unit')},
            },
        ),
        migrations.AddField(
            model_name='nursebloodrequest',
            name='used_stock_units',
            field=models.ManyToManyField(blank=True, related_name='blood_requests', through='nurse.NurseBloodRequestStockUnit', to='blood.stockunit'),
        ),
    ]
