# Generated by Django 4.2.23 on 2025-09-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0012_nursebloodrequeststockunit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='email',
        ),
    ]
