# Generated by Django 4.2.23 on 2025-09-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0013_remove_nurse_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='specialization',
            field=models.CharField(choices=[('Blood Bank Nurse', 'Blood Bank Nurse'), ('Transfusion Nurse', 'Transfusion Nurse'), ('Clinical Nurse Specialist', 'Clinical Nurse Specialist')], help_text='Select specialization relevant to blood donation', max_length=50),
        ),
    ]
