# Generated by Django 4.2.23 on 2025-09-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0014_alter_nurse_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='approved_at_admin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='approved_by_admin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='completed_at_admin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='completed_by_admin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rejected_by',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('nurse', 'Nurse'), ('system', 'System'), ('unknown', 'Unknown')], max_length=10, null=True),
        ),
    ]
