# Generated by Django 4.2.23 on 2025-10-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0015_stocktransaction_donor_blood_request_and_more'),
        ('nurse', '0015_remove_appointment_approved_at_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='donation_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='blood.donationcenter'),
        ),
    ]
