# Generated by Django 4.2.23 on 2025-10-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0016_appointment_barcode_appointment_donation_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
