# Generated by Django 4.2.23 on 2025-10-29 04:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nurse', '0017_remove_appointment_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nurse', 'verbose_name_plural': 'Nurses'},
        ),
        migrations.AddField(
            model_name='nurse',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the nurse was approved', null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this nurse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nurses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurse',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status - nurse cannot access system until approved'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief bio (max 500 characters)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone',
            field=models.CharField(default='N/A', help_text='Enter phone number in format: +999999999', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nurse',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB)', null=True, upload_to='nurse_profiles/'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='registration_number',
            field=models.CharField(help_text='Official nurse registration/license number (5-30 alphanumeric characters)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must be 5-30 characters (uppercase letters and numbers only).', regex='^[A-Z0-9]{5,30}$')]),
        ),
    ]
