# Generated by Django 4.2.23 on 2026-02-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nurse', '0018_alter_nurse_options_nurse_approved_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='approved_at_nurse',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='completed_at_nurse',
            new_name='collected_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='approved_by_nurse',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='completed_by_nurse',
        ),
        migrations.AddField(
            model_name='appointment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='approved_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse/Phlebotomist'), ('lab_tech', 'Lab Technologist'), ('blood_bank_tech', 'Blood Bank Technician'), ('system', 'System')], default='nurse', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse/Phlebotomist'), ('lab_tech', 'Lab Technologist'), ('blood_bank_tech', 'Blood Bank Technician'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='collected_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse/Phlebotomist'), ('lab_tech', 'Lab Technologist'), ('blood_bank_tech', 'Blood Bank Technician'), ('system', 'System')], default='nurse', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse/Phlebotomist'), ('lab_tech', 'Lab Technologist'), ('blood_bank_tech', 'Blood Bank Technician'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_received_at',
            field=models.DateTimeField(blank=True, help_text='When lab received the sample', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_tested_at',
            field=models.DateTimeField(blank=True, help_text='When lab completed testing', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_tested_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse/Phlebotomist'), ('lab_tech', 'Lab Technologist'), ('blood_bank_tech', 'Blood Bank Technician'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse/Phlebotomist'), ('lab_tech', 'Lab Technologist'), ('blood_bank_tech', 'Blood Bank Technician'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='safety_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('safe', 'Safe'), ('unsafe', 'Unsafe')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='safety_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='safety_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_verified_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='safety_verified_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse/Phlebotomist'), ('lab_tech', 'Lab Technologist'), ('blood_bank_tech', 'Blood Bank Technician'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sent_to_lab_at',
            field=models.DateTimeField(blank=True, help_text='When blood was sent to lab for testing', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_changed_by_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse/Phlebotomist'), ('lab_tech', 'Lab Technologist'), ('blood_bank_tech', 'Blood Bank Technician'), ('system', 'System')], help_text='Role of the person who last changed status', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('collected', 'Collected - Awaiting Testing')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='nurse_appoi_status_4b9f21_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['donor'], name='nurse_appoi_donor_i_11dd78_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='nurse_appoi_patient_a1158d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['-date'], name='nurse_appoi_date_5d20d0_idx'),
        ),
    ]
