# Generated by Django 4.2.23 on 2026-02-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0019_rename_approved_at_nurse_appointment_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nursebloodrequeststockunit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nursebloodrequeststockunit',
            name='blood_request',
        ),
        migrations.RemoveField(
            model_name='nursebloodrequeststockunit',
            name='stock_unit',
        ),
        migrations.DeleteModel(
            name='NurseBloodRequest',
        ),
        migrations.DeleteModel(
            name='NurseBloodRequestStockUnit',
        ),
    ]
