# Generated by Django 4.2.23 on 2026-02-28 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_bank_technician', '0001_initial'),
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_person', models.CharField(help_text='Lab in-charge name', max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('alternative_phone', models.CharField(blank=True, max_length=15)),
                ('has_blood_storage', models.BooleanField(default=True, help_text='Does hospital have blood bank fridge?')),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False, help_text='Has hospital been verified?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serving_centre', models.ForeignKey(blank=True, help_text='Which donation centre serves this hospital', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.donationcenter')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lab_tech', 'Laboratory Technician'), ('admin', 'Hospital Administrator'), ('viewer', 'View Only')], default='lab_tech', max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hospital.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaluser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital User',
                'verbose_name_plural': 'Hospital Users',
            },
        ),
        migrations.CreateModel(
            name='HospitalBloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units_requested', models.PositiveIntegerField()),
                ('units_dispatched', models.PositiveIntegerField(default=0)),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10)),
                ('patient_id', models.CharField(blank=True, help_text="Hospital's patient ID", max_length=50)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_license', models.CharField(blank=True, max_length=50)),
                ('urgency', models.CharField(choices=[('routine', 'Routine (24-48 hrs)'), ('urgent', 'Urgent (4-6 hrs)'), ('emergency', 'Emergency (Immediate)')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Ready for Pickup'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered to Hospital'), ('partially_dispatched', 'Partially Dispatched'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected - No Stock')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hospital_requests', to='blood_bank_technician.bloodbanktechprofile')),
                ('assigned_centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_requests', to='blood.donationcenter')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_hospital_requests', to='blood_bank_technician.bloodbanktechprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='hospital.hospital')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_made', to='hospital.hospitaluser')),
            ],
            options={
                'verbose_name': 'Hospital Blood Request',
                'verbose_name_plural': 'Hospital Blood Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hospitaluser',
            index=models.Index(fields=['hospital', 'role'], name='hospital_ho_hospita_311476_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaluser',
            index=models.Index(fields=['is_active'], name='hospital_ho_is_acti_db24bd_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaluser',
            index=models.Index(fields=['role'], name='hospital_ho_role_aad64a_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitaluser',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_hospitaluser_user'),
        ),
        migrations.AddConstraint(
            model_name='hospitaluser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_contact', True)), fields=('hospital',), name='unique_primary_contact_per_hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitaluser',
            unique_together={('hospital', 'user')},
        ),
    ]
