# Generated by Django 4.2.23 on 2026-03-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the blood was delivered to the hospital', null=True),
        ),
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='delivered_by',
            field=models.ForeignKey(blank=True, help_text='Hospital staff who confirmed delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_requests', to='hospital.hospitaluser'),
        ),
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Notes about the delivery'),
        ),
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='When the blood was received at the hospital', null=True),
        ),
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='received_by_name',
            field=models.CharField(blank=True, help_text='Name of hospital staff who received the blood', max_length=200),
        ),
        migrations.AddIndex(
            model_name='hospitalbloodrequest',
            index=models.Index(fields=['status'], name='hospital_ho_status_67cae2_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbloodrequest',
            index=models.Index(fields=['hospital', 'status'], name='hospital_ho_hospita_75db5a_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbloodrequest',
            index=models.Index(fields=['blood_group'], name='hospital_ho_blood_g_56e1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbloodrequest',
            index=models.Index(fields=['request_number'], name='hospital_ho_request_b3a025_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbloodrequest',
            index=models.Index(fields=['delivered_at'], name='hospital_ho_deliver_bcd0ba_idx'),
        ),
    ]
