# Generated by Django 4.2.23 on 2026-02-27 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0002_remove_hospital_address_remove_hospital_town_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaluser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaluser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hospitaluser',
            index=models.Index(fields=['hospital', 'role'], name='hospital_ho_hospita_311476_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaluser',
            index=models.Index(fields=['is_active'], name='hospital_ho_is_acti_db24bd_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaluser',
            index=models.Index(fields=['role'], name='hospital_ho_role_aad64a_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitaluser',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_hospitaluser_user'),
        ),
        migrations.AddConstraint(
            model_name='hospitaluser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_contact', True)), fields=('hospital',), name='unique_primary_contact_per_hospital'),
        ),
    ]
